### ISSUE TITLE
code_challenge_methods_supported is missing in the OIDC Provider metadata

### ISSUE THREAD

**Issue by hectorj2f** [vmware-tanzu/pinniped#1107]
**Is your feature request related to a problem? Please describe.**

When using certain OIDC providers, I saw `code_challenge_methods_supported` is not propagated as part of the metadata (https://github.com/vmware-tanzu/pinniped/blob/main/internal/oidc/discovery/discovery_handler.go#L19) we get from the OIDC provider. This becomes problematic as the authorization server can throw error as PKCE is not support. 

**Describe the solution you'd like**

A possible solution could be to add `code_challenge_methods_supported` as part of the OIDC Provider Metadata https://github.com/vmware-tanzu/pinniped/blob/main/internal/oidc/discovery/discovery_handler.go.

**Comment by cfryanr** [comment]
I'm not exactly sure what problem you were facing, but as an aside it might be more correct for us to include that key as you’re suggesting, since https://datatracker.ietf.org/doc/html/rfc8414#section-2 says, “If omitted, the authorization server does not support PKCE.” Since the Supervisor does support and require PKCE, it should have that key in the discovery document.

The spec says that it should be a JSON array, so it should look like this in the discovery response:
`"code_challenge_methods_supported": [ "S256" ],`

Adding that to the discovery response may not solve your problem though. What problem were you having?

**Comment by hectorj2f** [comment]
Yes, I am using a client that relies on the metadata endpoint to determine if PKCE is supported. For instance, when I reach `https://accounts.google.com/.well-known/openid-configuration`, I can see:

```
 "code_challenge_methods_supported": [
  "plain",
  "S256"
 ],
 ```

**Comment by anjaltelang** [comment]
@hectorj2f Thank you for submitting this issue. This does seem important but our maintainer team has other feature work that is ongoing and will pick this issue up once they are available. In the meantime, if you're interested in making a PR, we'd be happy to review it. Here's how to contribute to the project https://github.com/vmware-tanzu/pinniped/blob/main/CONTRIBUTING.md. Do reach out to us on slack in the Kubernetes/Pinniped channel incase you have any questions.

**Comment by hectorj2f** [comment]
@anjaltelang  @cfryanr I opened this PR https://github.com/vmware-tanzu/pinniped/pull/1127
