### ISSUE TITLE
Have you considered alternatives to bcrypt?

### ISSUE THREAD

**Issue by simonfelding** [vmware-tanzu/pinniped#1488]
**Is your feature request related to a problem? Please describe.**

bcrypt is pretty old fashioned (and well known, which is great). It's pretty expensive.

**Describe the solution you'd like**

Use a [NIST recommended hashing algorithm instead (section 5.1.1.2)](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-63b.pdf). 

**Describe alternatives you've considered**

BALLOON and PBKDF2 are recommended by NIST. BALLOON is proven memory-hard. PBKDF2 is fast.

**Are you considering submitting a PR for this feature?**
No.

- **How will this project improvement be tested?**
Compare the resource use of bcrypt with BALLOON and PBKDF2.
- **How does this change the current architecture?**
It will not change the architecture except for using a different hashing algorithm.
- **How will this change be backwards compatible?**
By prefixing the hash with the name of its derivation method and a terminating letter not in the bcrypt alphabet (./ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789) such as !. It will then be safe to assume that unprefixed hashes are bcrypt hashes.
- **How will this feature be documented?**
Search and replace in design docs and documentation.

- **additional information**
I would rather have faster hashing than a slow and resource intensive algorithm. Maybe it could be an option? I appreciate you dont store the plaintext by the way, very nice!

**Comment by cfryanr** [comment]
Thanks for creating the issue, @simonfelding.

I'm not an expert in hashing algorithms for passwords, but I took a look at the NIST docs. That section of the doc which recommends password hashing algorithms refers to SP 800-132, which is an old doc currently under review (see https://csrc.nist.gov/projects/crypto-publication-review-project for review timetable). The initial community response, which was just closed a couple months ago and summarized in https://csrc.nist.gov/csrc/media/Projects/crypto-publication-review-project/documents/initial-comments/sp800-132-initial-public-comments-2023.pdf, has been very negative in regard to NIST including BALLOON in the docs. They also point out that PBKDF2 is considered insufficient by today's standards. Several folks are recommending scrypt and variations of Argon2. It feels like we should wait to see how this shakes out before following any NIST advice.

bcrypt is indeed old, but still considered appropriate (as far as I know) due to its tunable number of cycles, which can be fast enough for use in an interactive web application login flow while being slow enough to make password cracking inconvenient. I've read that Argon2 is even slower, so it may not be appropriate for that use case. Some developers seems to prefer scrypt based on some quick googling for comparison articles. bcrypt and the newer alternatives argon2 and scrypt are all included in golang.org/x/crypto, so they are all maintained by the golang team, which is nice.

**Comment by simonfelding** [comment]
I wasn't aware of that, thank you for the thorough reply. I'm no expert either, that's why I would stick to official guidelines. Those comments are a fascinating read! bcrypt definitely seems like a very good choice as a balance between speed and security.

**Comment by cfryanr** [comment]
Ok, thanks. I'm going to close this for now, but this conversation will remain in searchable GitHub issues history. In the future, we might want to consider switching to something more modern like scrypt, but there's nothing specifically driving us to do so at the moment. If you're still interested, please let us know when NIST updates their guidance.
