### ISSUE TITLE
Add Carvel package proposal (please update with more detail)

### ISSUE THREAD

**Issue by joshuatcasey** [vmware-tanzu/pinniped#1614]
We should add a proposal that answers at least the following questions:

- Will there be separate Carvel packages for Supervisor/Concierge?
- Where will the packages be released (github releases? dockerhub?)
- sample installation instructions
- brief description of whether we will continue with the simpler `ytt` manifests or just use the carvel package. If we continue to support both, when should a user use one or the other?
- listing (either positive or negative) of which resources will be deployed via the carvel package
  - positively by listing out all of the K8s resources explicitly
  - negatively by listing out which resources/CRs are NOT deployed (probably such as `*IdentityProviders`, `FederationDomain`, etc.
- Do we need a schema for the ytt data values?
- Should the carvel package reside in this repository?
- Should we reuse, refactor, or remove the `deploy` directory?
- Should integration tests use the carvel package?

**Comment by voor** [comment]
I would recommend having a separate package for the concierge and the supervisor.

The concierge should be on *every* cluster that you deploy into your environment. The values that are passed to the concierge, while there is a large overlap with the supervisor, are going to be "commonly shared" values.  In particular, the concierge is intentionally missing _some_ things like credentials to your upstream IDP.  The supervisor values are very specific, and handled differently.  If you want to create a full gitops environment that is passing things across your clusters you're put in a weird position when it comes to your supervisor:
* Do you _exclude_ the pinniped package from common and include pinniped on the cluster that is running the supervisor?
* Do you have a weird conditional everywhere pinniped is installed so that it also sets up the supervisor on the cluster you intend to have it on?

Here's an example of the conditional approach, which is a tad messy -- I end up passing into *every cluster* values that I don't want there, specifically the ones for setting up the [upstream credentials.](https://gitlab.com/tanzuplatform/platform-services/-/blob/main/stack/common/values/ghost/secrets.ghost.sops.yaml?ref_type=heads#L9-19) and then you also have a [messy conditional](https://gitlab.com/tanzuplatform/platform-services/-/blob/main/stack/common/manifests/pinniped.yaml?ref_type=heads#L38-43)

Most gitops can handle passing down common values to both a supervisor package and a concierge package, and they can also handle upgrading both of those packages in tandem (although Pinniped should handle version drift within reason anyway)

**Comment by benjaminapetersen** [comment]
[in progress, will edit & update until complete.....]

My suggestions for the questions, potentially leading to a [formal proposal](https://github.com/vmware-tanzu/pinniped/tree/main/proposals) if we see fit:
- Q: Will there be separate Carvel packages for Supervisor/Concierge?
  - A:  Yes, I agree with @voor above, there should be 2 separate packages for these.  The configuration is different and it is easier to reason about.  There is a "one supervisor" but potentially "many concierge" kind of model that lends to this pattern.
- Q: Where will the packages be released (github releases? dockerhub?)
- Q: Sample installation instructions
- Q: Brief description of whether we will continue with the simpler ytt manifests or just use the carvel package. If we continue to support both, when should a user use one or the other?
- Q: Listing (either positive or negative) of which resources will be deployed via the carvel package
   - positively by listing out all of the K8s resources explicitly
   - negatively by listing out which resources/CRs are NOT deployed (probably such as *IdentityProviders, FederationDomain, etc.
- Q: Do we need a schema for the ytt data values?
- Q: Should the carvel package reside in this repository?
- Q: Should we reuse, refactor, or remove the deploy directory?
- Q: Should integration tests use the carvel package?

**Comment by benjaminapetersen** [comment]
Some additional questions:
- Q: If we change from a `values.yaml` file to a `schema` file, does that change the existing user experience for YTT?
   - A: The schema file provides validation that basic YTT does not.  If we migrated the `./deploy/values.yaml` to be a schema file, then we can expect user experience to change in that ytt will complain more aggressively about values it is unhappy with.  
   - A: We could opt to keep the `./deploy/values.yaml` file as-is and also support a `./deploy_carvel_package/values-schema.yaml` file as well, but I don't see us being happy with that decision.
- Q: Would changing our `values.yaml` to a `values-schema.yaml` file affect our CI?
   - A: Probably, but I don't expect that our CI is passing any invalid values today.

- Q: What happens when a `PackageRepository` drops a version of a package running on the cluster?
   - In more complex terms:
     - `PackageRepository` named `FooRepo` at version `1` supports `BarPackage` at versions 1,2,3,4,5,6
     - User deploys `BarPackage` at version `2`.
     - User upgrades the `PackageRepository` to version `2`.
     - The `PackageRepository` at version 2 has chosen to support `BarPackage` at only 3,5,6,7
        -  Version 1 & 2 of `BarPackage` is dropped because it is no longer supported
        - Version 4 of `BarPackage` is dropped because it introduced a terrible security issue and should not be used
   - Now, what happens to the current running version of `BarPackage` at version 2?
      - It is no longer part of the `PackageRepository`.
      - Is it automatically uninstalled?
      - Can it be upgraded?
    - A: TODO, unknown.  Opinions:
      - My hope would be that the Carvel toolset does not allow the upgrade unless the new version of the `PackageRepository` supports all running package versions it is responsible for.
      - The package ought not be uninstalled simply because the PackageRepository is upgraded
        - Nevertheless, I would be concerned about the Package
      - The package ought be able to be upgraded
