### ISSUE TITLE
Session expires based on ID Token instead of Access Token

### ISSUE THREAD

**Issue by dmeijboom** [vmware-tanzu/pinniped#1629]
**What happened?**

We have several clusters which are running pinniped's Concierge (without Supervisor) version `v0.25.0` on GKE (Kubernetes version 1.24.x).
Each cluster has their own `JWTAuthenticator` with the details of their own OIDC identity provider/client.

Our OIDC IDP doesn't respond with a refresh token (which isn't used anyway for JWT authentication if I remember correctly) and contains both an ID token and an access token. The access token expires in 1 hour while the ID token expires in 5 minutes. Authentication works but the session expires after five minutes.

Claims example:

```yaml
tokens:
  access:
    expiryTimestamp: "2023-08-17T10:28:17Z"
    token: <REDACTED>
  id:
    claims:
      exp: 1692263993
      iat: 1692264497
      <REDACTED>
```

The access token is a JWT which contains the following `exp`/`iss` claims:

```json
{
  "exp": 1692268097,
  "iat": 1692264497
}
```

**What did you expect to happen?**

I would expect the session to be valid for an hour as the access token expires after an hour (`3600` seconds if you look at the `exp`/`iss` claims).

**What is the simplest way to reproduce this behavior?**

1. Setup a `JWTAuthenticator`
2. Make sure that the upstream IDP returns an ID token which expires after a couple of minutes
3. Wait a couple of minutes
4. Try any `kubectl (..)` command
5. Pinniped required re-authentication

**In what environment did you see this bug?**
- Pinniped server version: `v0.25.0`
- Pinniped client version: `version.Info{Major:"0", Minor:"25", GitVersion:"v0.25.0", GitCommit:"c7b49d9b93d9f293f81f270054e9f67c2ba7f181", GitTreeState:"clean", BuildDate:"", GoVersion:"go1.21.0", Compiler:"gc", Platform:"darwin/arm64"}`
- Pinniped container image (if using a public container image): `projects.registry.vmware.com/pinniped/pinniped-server:v0.25.0@sha256:50989db714555e375f68f0424bec3ad752d2658f624e5abd12cca3a4`
- Pinniped configuration (what IDP(s) are you using? what downstream credential minting mechanisms are you using?): can't give many details but we are using DUO's OIDC Relaying Party feature
- Kubernetes version (use `kubectl version`): `v1.24.x`
- Kubernetes installer & version (e.g., `kubeadm version`): n/a
- Cloud provider or hardware configuration: GKE
- OS (e.g: `cat /etc/os-release`): n/a
- Kernel (e.g. `uname -a`): n/a
- Others:

**What else is there to know about this bug?**

I tried looking for existing issues and searching through the code but couldn't find any more details.

**Comment by cfryanr** [comment]
Hi @dmeijboom, thanks for creating an issue.

I think what you are seeing is by design, although I can understand why you were hoping for a different behavior. I can try to explain and I can also propose some potential solutions.

When you use a JWTAuthenticator what you are saying is conceptually "when anyone shows up at this cluster's front door holding a JWT from the expected issuer with the expected audience claim, then allow them to authenticate as the username from the configured username claim of the JWT and group memberships from the configured groups claim of the JWT". The cluster (the Concierge, more specifically) is only presented with the ID token. It does not receive the access token nor any other information, so it has no other information to work from. That JWT must not be expired. The JWTAuthenticator code is actually borrowed from Kubernetes, and is performing the exact same checks as Kubernetes own OIDC authenticator. Also note that OIDC does not require that access tokens be JWTs, and in fact they are often opaque tokens with no way to know their lifetime by only looking at the token itself, so in general an access token would not be enough information to imply a longer lifetime all by itself anyway, which is probably one of the reasons why the Kubernetes code does not use access tokens in addition to the ID token for auth.

However, there are possible solutions.

1. If your OIDC provider issued refresh tokens, then the Pinniped CLI would notice that the ID token is expired and it would use the refresh token to attempt to get a new ID token that it could send to the cluster. This would happen without any need for user interaction, so it would feel seamless.
2. If you use the Pinniped Supervisor, then it will issue its own ID, access, and refresh tokens after the user has authenticated with your external OIDC provider. The Pinniped CLI would perform refreshes against the Supervisor using the Supervisor-issued refresh token, and during those refreshes the Supervisor would use either the external provider's refresh token (preferred) or the external provider's access token (if there was no refresh token handed out by the external provider) to make various calls to your external provider to determine if the user's session should be allowed to continue.

Either of those approaches should allow the user's session to continue longer without any user interaction.

Does that help?

**Comment by dmeijboom** [comment]
Thanks for the detailed reply. I wasn't aware that the JWTAuthenticator only looks at the ID token. That makes sense. Our OIDC provider should simply reply with refresh tokens, I guess that's the easiest way to move forward.

Thanks again! I'll close this issue as its exactly how pinniped should work.
