### ISSUE TITLE
Removing the concierge secret makes ingress-nginx reload fail

### ISSUE THREAD

**Issue by aslafy-z** [vmware-tanzu/pinniped#1722]
**What happened?**

When Pinniped Concierge regenerate it's certificate, ingress-nginx emits a reload fail event and bumps the associated metric value.

```
Error reloading NGINX: 
-------------------------------------------------------------------------------
Error: exit status 1
nginx: [emerg] cannot load certificate "/etc/ingress-controller/ssl/pinniped-concierge-tls-pinniped-concierge.pem": PEM_read_bio_X509_AUX() failed (SSL: error:0909006C:PEM routines:get_name:no start line:Expecting: TRUSTED CERTIFICATE)
nginx: configuration file /tmp/nginx/nginx-cfg3189152186 test failed-------------------------------------------------------------------------------
```

**What did you expect to happen?**

ingress-nginx reloads without error.

This can be done by replacing the secret with the updated value instead of [removing it](https://github.com/vmware-tanzu/pinniped/blob/main/internal/controller/apicerts/certs_expirer.go) and waiting for the [other controller to recreate](https://github.com/vmware-tanzu/pinniped/blob/main/internal/controller/apicerts/certs_manager.go) an up to date one.

**What is the simplest way to reproduce this behavior?**

- Deploy ingress-nginx with it's default values.
- Deploy pinniped-concierge with a very low `api.servingCertificate.durationSeconds` settings: https://github.com/vmware-tanzu/pinniped/blob/0c4e3aa5f1471746ea674d023a30da0d9b4e717e/deploy/concierge/deployment.yaml#L65.
- Create an ingress for pinniped-concierge that uses the pinniped generated certificate.
- Stare at nginx logs for errors (or check `count(nginx_ingress_controller_config_last_reload_successful == 0) > 0`)

**In what environment did you see this bug?**
- Pinniped server version: v0.27.0
- Pinniped client version: v0.27.0
- Pinniped container image (if using a public container image): v0.27.0
- Pinniped configuration (what IDP(s) are you using? what downstream credential minting mechanisms are you using?): -
- Kubernetes version (use `kubectl version`): v1.25
- Kubernetes installer & version (e.g., `kubeadm version`): -
- Cloud provider or hardware configuration: -
- OS (e.g: `cat /etc/os-release`): -
- Kernel (e.g. `uname -a`): -
- Others: -

**What else is there to know about this bug?**

**Comment by cfryanr** [comment]
Hi @aslafy-z,

Thanks for creating an issue! I assume you are using an ingress for the Concierge's impersonation proxy port?

As you've noted, there are certain TLS certs that are auto-created and auto-rotated. Be careful here though, the `api.servingCertificate.durationSeconds` controls the rotation of a different auto-generated TLS certificate. That cert is used to help register the Concierge as an aggregated API server with the Kubernetes API server (on the `APIService` resource). That cert is only used inside the cluster between the Kubernetes API server and the Concierge, and should not be used for the impersonation proxy (which serves traffic from clients that are outside the cluster). You should not need to use an ingress controller for this, because the installation manifest yaml will create a `ClusterIP` service for this purpose, and it should only receive traffic from inside the cluster (more specifically only from the Kubernetes API server).

As you've seen, the default behavior of the impersonation proxy is to create its own CA, create its own TLS certificate, create a load balancer service, and start serving traffic using the IP of the load balancer service as the ingress address for clients. This auto-generated TLS certificate has a 100 year expiration and will not be rotated by default. (It is created by [this controller](https://github.com/vmware-tanzu/pinniped/blob/v0.27.0/internal/controller/impersonatorconfig/impersonator_config.go#L1034).)

The default behavior is probably fine for simple use cases, but for Concierge admins who have more complex networking/ingress requirements it may not be sufficient. For example, if you need to use an ingress for all incoming traffic to the cluster, then you might not want to have a separate load balancer for the impersonation proxy.

That's why you are able to change the service that the Concierge will create, if you do not prefer to use a load balancer. You can tell it to create a `ClulsterIP` service instead of an LB service, or you can tell it not to create a service at all because you prefer to create your own. You can configure this in the `CredentialIssuer.spec` (see [docs](https://github.com/vmware-tanzu/pinniped/blob/main/generated/1.28/README.adoc#credentialissuerspec)).

In recent versions of Pinniped, there is a new feature where you can now also control the TLS certs to be served by the impersonation proxy. (See [blog post](https://pinniped.dev/posts/v0-25-0-external-cert-mgmt-impersonation-proxy/) for a detailed example of how to use this.) This, together with being able to create your own service, gives you almost complete control over ingress and TLS works for your impersonation proxy on each cluster.

Please let us know if that explanation helps, or if you have any more questions about setting up ingress for the Concierge.

**Comment by cfryanr** [comment]
Hi @aslafy-z, did the above comment help? I didn't hear back from you so I will close this issue for now, but please feel free to add questions/comments or reopen the issue.
