### ISSUE TITLE
Hello, I have a self-built cluster, but my kube-controller-manager is a binary program, not a container. Can pinniped be connected using the first token method?

### ISSUE THREAD

**Issue by riven-blade** [vmware-tanzu/pinniped#2073]
**Is your feature request related to a problem? Please describe.**

Token Credential Request API: Can be run on any Kubernetes cluster where a custom pod can be executed on the same node running kube-controller-manager. This type of cluster is typically called “self-hosted” because the cluster’s control plane is running on nodes that are part of the cluster itself. Most managed Kubernetes services do not support this.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Are you considering submitting a PR for this feature?**

- **How will this project improvement be tested?**
- **How does this change the current architecture?**
- **How will this change be backwards compatible?**
- **How will this feature be documented?**

**Additional context**

**Comment by cfryanr** [comment]
Hi @riven-blade,

The Pinniped Concierge has two modes of operation. If your cluster does not run the kube-controller-manager as a pod, then the Concierge will automatically detect that and run the impersonation proxy. Then the `pinniped get kubeconfig` command will auto-detect that, and generate the kubeconfig appropriately for that cluster. The other alternative is to use the Pinniped Supervisor without any Concierge for that cluster, by configuring the flags of the Kubernetes API server to use the Supervisor as its OIDC provider. We have documentation for that [here](https://pinniped.dev/docs/tutorials/supervisor-without-concierge-demo/).

I'm going to close this issue for now because there is no detail or questions in the description. Please feel free to let us know if you still have questions.
