### ISSUE TITLE
Pinniped Kube-Cert-Agent Does Not Recover from Cluster Shutdown/Restart

### ISSUE THREAD

**Issue by doddatpivotal** [vmware-tanzu/pinniped#493]
**What happened?**

I had deployed TKG 1.3 RC3 to AWS.  1 Management Cluster and 2 Workload Clusters.  The workload clusters were also instrumented with TMC.

I stopped my AWS instances overnight to save cost.  When I restarted the clusters.  (control plane's first, then workload workers, then management cluster workers).  Pods came up an running, except the pinniped-conceriege-kube-cert-agent pods.

These pods showed that 0/1 container were ready, and the status was unknown.

I manually deleted the pods and then the replacement pods came up fine.

**What did you expect to happen?**

I expected these pods to come back in a ready state.

**What else is there to know about this bug?**
I'm not sure what version of pinniped TMC deployed, but TKG 1.3 deployed pinniped 0.4.1.

**Comment by mattmoyer** [comment]
Thanks for filing @doddatpivotal. I think I have seen this locally when developing with Kind also. The pods come back online but something about the kube-cert-agent controller wasn't working as expected.

**Comment by enj** [comment]
We need to update the deletion logic to also delete pods that are unhealthy or in an unknown state for more than a minute or so.

**Comment by mattmoyer** [comment]
I think we should tackle this bug by refactoring the kube-cert-agent controllers to manage a Deployment instead of a bare Pod. This should simplify the code a bit and make it handle edge cases like this much better.

**Comment by mattmoyer** [comment]
Quick followup note for anyone coming across this issue... We fixed this bug in two different ways:

1. In Pinniped v0.4.2, we fixed the kube-cert-agent "deleter" controller to recognize pods that are in an unhealthy state and clean them up so they can be recreated (#580).

1. In Pinniped v0.8.0 (not yet released), we rewrote this code to be more robust and use a Deployment (#569).

If you're currently running a v0.4.x release, upgrading to v0.4.2 should resolve the issue. Otherwise, you're best off waiting for v0.8.0, and as a workaround you can recover a stuck cluster by deleting the agent pods with `kubectl delete pods -A -l kube-cert-agent.pinniped.dev`.
